### ISSUE TITLE
robotic parsing panic

### ISSUE THREAD

**Issue by jdm** [jdm/mzxplay#63]

**Comment by jdm** [comment]
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `-1`', /Users/jdm/src/libmzx/src/robotic.rs:1601:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:340
   7: libmzx::robotic::parse_program
             at /Users/jdm/src/libmzx/src/robotic.rs:1601
   8: libmzx::load_robot
             at /Users/jdm/src/libmzx/src/lib.rs:1626
   9: libmzx::load_board
             at /Users/jdm/src/libmzx/src/lib.rs:1918
  10: mzxplay::run
             at src/main.rs:142
  11: mzxplay::main
             at src/main.rs:234
  12: std::rt::lang_start::{{closure}}
             at /rustc/d22fa2d87d03d19fdb1359faab9ec5e74eff26b3/src/libstd/rt.rs:64
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:92
  15: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  16: std::rt::lang_start
             at /rustc/d22fa2d87d03d19fdb1359faab9ec5e74eff26b3/src/libstd/rt.rs:64
  17: mzxplay::main
```

**Comment by jdm** [comment]
Fixed by https://github.com/jdm/libmzx/commit/18b73dc80485f5987c96455d5eae646b7d34daa1.
